imjanny/imjanny.github.io

.gitignore, base.html/index.html, base.html/login.html, base.html/signup.html, static/css/login.css, static/css/signup.css, static/js/api.js, static/js/login.js, static/js/signup.js
gitignore .vscode추가 / api.js 공통적용기능 추가
=> :sparkles: Feat: signup, login, logout api연결 #4 #5

static/css/login.css, static/js/login.js, user/login.html
=> :ambulance: Naver login url hotfix

static/css/login.css, static/css/password_change.css, static/js/api.js, static/js/login.js, static/js/password_reset.js, static/js/password_reset_confirm.js, static/js/signup.js, user/login.html, user/password_change.html, user/password_reset_confirm.html, user/password_reset_failed.html, user/signup.html
password_reset, reset_confirm html,css,js / password_change(변경) 추가, login.css 인풋박스 테두리 보이게 수정
=> :sparkles: Feat: 비밀번호 재설정, 확인 api연결 #5

article/detail.html, static/css/detail.css
게시글 상세 페이지 html 작성!(article 폴더 생성, detail_css, js 파일 생성)
=> ✨ Feat: create article/detail_html #8, #9, #10, #11

static/css/profile_page.css, static/js/profile_page.js, static/js/subscribe_list.js, user/profile_page.html
1. 프로필 페이지 : 구독 여부 기능 추가
2. 구독자 목록 : 나의 구독자 리스트 페이지일 경우 구독 취소 버튼 추가
=> ⚡ Feat: 프로필 페이지, 구독자 목록 업데이트 #6, #7

static/js/create_article.js, static/js/nav.js, static/js/search.js, static/js/signup.js
search.js base_url주석처리, signup.js alert추가
=> :bug: Fix: 글작성 400, profile_imb 수정, 회원가입 정규식 alert 추가 #4 #6 #8

base/index.html, base/nav.html, static/js/category.js, static/js/login.js, static/js/nav.js, static/js/profile_edit.js, static/js/profile_page.js, static/js/search.js, user/article_list.html, user/kakaocode.html, user/login.html, user/profile_page.html
=> ✨ FEAT : create category #12

article/detail.html, article/detail_update.html, static/css/detail.css, static/js/detail.js, static/js/detail_update.js
=> ⚡ Feat: update article_detail_page #8

article/create_article.html, base/index.html, static/css/index.css, static/js/index.js
create_article.html, index.html,css,js 수정
=> :ambulance: Fix: 카테고리 value변경, 메인페이지 back-to-top추가 #8 #47

article/detail.html, article/detail_update.html, static/js/detail.js, static/js/detail_update.js
=> ⚡ Feat: update article_detail #8, #10

article/detail.html, static/css/detail.css, static/js/detail.js, static/js/profile_page.js, user/profile_page.html
프로필 페이지 : 스크랩 목록 추가
게시글 상세 페이지 : 댓글 페이지 네이션 추가
=> ⚡ Feat: update aticle_detail/profile_page

base/index.html, base/nav.html, static/css/index.css, static/js/index.js
index.html,css,js / nav.html에서 today삭제
=> :sparkles: Feat: 오늘의 hot뉴스추가, 기자구독 12명제한, 날짜 추가 #47

static/css/message_create.css, static/css/message_detail.css, static/css/message_inbox.css, static/css/message_sent.css, static/js/message_create.js, static/js/message_detail.js, static/js/message_inbox.js, static/js/message_reply.js, static/js/message_sent.js, user/message_create.html, user/message_detail.html, user/message_inbox.html, user/message_reply.html, user/message_sent.html
=> :sparkles:Feat: 쪽지 답장 프론트 완성 #52

article/detail.html, article/detail_update.html, static/css/detail.css, static/css/detail_comment.css, static/css/detail_update.css, static/css/profile_page.css, static/js/detail.js, static/js/detail_comment.js, static/js/profile_page.js, user/profile_page.html
=> ⚡ Feat: update article.detail/detail_update page #8, #10, #11

nav.html, static/css/index.css, static/js/api.js, static/js/index.js, static/js/signup.js, user/password_change.html
api.js/index.js/signup.js/password_change.html/nav.html 수정
=> :zap: Fix: 메인기사title추가/api.js수정/password_change수정 #47

static/js/detail.js, static/js/detail_comment.js, static/js/profile_page.js
=> 🩹 Feat: change noprofileimage

static/css/index.css, static/js/api.js
=> :art: 메인페이지 css 수정 #47

article/detail.html, static/css/profile_page.css, static/js/api.js, static/js/detail.js, static/js/detail_comment.js, static/js/profile_page.js, user/profile_page.html
=> :zap: Fix: 로그인 안했을 경우 게시글, 프로필 보기 가능 #6, #8

article/create_article.html, article/detail.html, article/detail_update.html, static/css/create_article.css, static/css/detail.css, static/css/detail_update.css, static/css/profile_page.css, static/css/subscribe_list.css, static/js/create_article.js, static/js/detail.js, static/js/detail_update.js, static/js/message_profile_user_send.js, static/js/profile_page.js, user/message_profile_user_send.html, user/profile_page.html
1. 게시글 작성하기 : 사진 설명 추가
2. 프로필 페이지 : 제보하기 링크 변경
=> ⚡ Feat: create_article) add article image content #8 / profile_page) update message link #6

index.html
=> :zap: Fix: 메인기사title 누락 추가 #47

static/css/detail.css, static/js/detail.js, static/js/detail_comment.js
=> 🩹 Fix: comment profile_img #10

static/css/index.css
=> :art: Fix: 메인css 수정 #47

static/js/profile_page.js, static/js/subscribe_list.js
프로필 페이지 스크랩 목록 수정 완료(다른 유저의 프로필 페이지에서도 나의 스크랩 목록으로 표시된 부분)
=> 🩹 Fix: profile_page scrap list #6

user/login.html
=> :ambulance: Fix: 로그인페이지 버튼 경로 수정 #5

user/kakaocode.html
=> :bug: FIX: kakao login fix

static/js/detail.js, static/js/index.js
=> :ambulance: Fix: 메인 hot뉴스, 기자구독 지연시간 수정, 게시글 삭제 시 이동경로 수정 #47

static/js/login.js
=> 🚑 Fix: 메인 hot뉴스, 기자구독 지연시간 수정, 게시글 삭제 시 이동경로 수정 #47

nav.html, static/css/nav.css, static/js/message.js, static/js/message_detail.js, static/js/message_inbox.js, static/js/message_sent.js, static/js/nav.js, static/js/profile_edit.js, user/message_inbox.html, user/message_sent.html
새 쪽지 알림 기능 추가 : 안읽은 쪽지 왔을 시 nav bar 쪽지 수 표시
(+ 쪽지 두번 클릭 시 열림/닫힘 개선 완료)
=> ✨ Feat: add new message count #52

static/css/detail.css, static/js/create_article.js, static/js/detail.js
기사 요약 왼쪽정렬, 기사 작성 완료 시 AI가 기사를 자동 요약해준다는 것을 고지, 글자수 지키지 않으면 alert 경고
=> 🩹Fix: 기사 요약하기 기능 자잘한 수정 #131

static/css/article_list.css, static/css/profile_page.css, static/css/search.css, static/js/category.js, static/js/detail.js, static/js/detail_comment.js, static/js/profile_page.js, static/js/search.js, static/js/subscribe_list.js, user/profile_page.html, user/subscribe_list.html
1. 게시글 상세보기 스크롤 이동 수정
2. 프로필 페이지 스크랩 취소 버튼 추가
3. 프로필 페이지 이메일 알림 설정 추가
4. 게시글 목록(+검색) 카테고리 추가
=> ⚡ Fix: detail) update scroll move #9, #10

static/css/article_list.css, static/css/profile_page.css, static/css/search.css, static/js/category.js, static/js/detail.js, static/js/detail_comment.js, static/js/profile_page.js, static/js/search.js, static/js/subscribe_list.js, user/profile_page.html, user/subscribe_list.html
Reverts imjanny/imjanny.github.io#135
=> Revert "⚡ Fix: detail) update scroll move #9, #10"

static/js/index.js, static/js/profile_page.js
index.js, profile_page.js-탈퇴하면 로컬스토리지 삭제
=> :zap: Fix: 날씨 백엔드 수정->index.js 수정 #136

static/js/profile_page.js
=> 🩹 Fix: scrapList cancle button move #6

article/article_list.html, article/create_article.html, article/detail.html, article/detail_update.html, index.html, static/css/index.css, user/kakaocode.html, user/login.html, user/message.html, user/message_create.html, user/message_detail.html, user/message_inbox.html, user/message_profile_user_send.html, user/message_reply.html, user/message_sent.html, user/password_change.html, user/password_reset.html, user/password_reset_confirm.html, user/password_reset_failed.html, user/privacy.html, user/profile.html, user/profile_page.html, user/signup.html, user/subscribe_list.html
=> :zap: Fix: 모든페이지 Favicon 적용 및 title 수정

article/article_list.html, article/create_article.html, article/detail.html, article/detail_update.html, index.html, static/css/index.css, static/js/profile_page.js, user/kakaocode.html, user/login.html, user/message.html, user/message_create.html, user/message_detail.html, user/message_inbox.html, user/message_profile_user_send.html, user/message_reply.html, user/message_sent.html, user/password_change.html, user/password_reset.html, user/password_reset_confirm.html, user/password_reset_failed.html, user/privacy.html, user/profile.html, user/profile_page.html, user/signup.html, user/subscribe_list.html
=> ⚡ Fix: 모든페이지 Favicon 적용 및 title 수정

README.md
=> :memo: Feat: README 추가

static/css/index.css, user/login.html
=> :ambulance: Fix: 광고 media추가/ 로그인페이지 에러 수정
